<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BusinessCentral_API</RootNamespace>
    <UserSecretsId>85dbeb58-b712-4ec7-b7d3-d2ee1d53ca02</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" /> -->
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <ProjectReference Include="..\API_Management\API_Management.csproj" />
  </ItemGroup>
</Project>
